import Link from "next/link"
import { ArrowLeftIcon } from "@/components/ArrowLeftIcon"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="mx-auto flex min-h-screen w-full sm:max-w-2xl sm:flex-row">
      {/* TODO: サイドメニューを実装し次第入れる */}
      <div className="w-[147px] border-l">サイドメニュー</div>
      <div className="flex-1 border">
        <div className="flex h-12 items-center gap-x-4 border-b px-4 py-3">
          {/* TODO: ページ作成後リンクの差し替え */}
          <Link href={"/"}>
            <ArrowLeftIcon />
          </Link>
          <p className="font-bold text-[#020010] text-opacity-[0.57]">下書き</p>
        </div>
        {children}
      </div>
    </div>
  )
}
