export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="mx-auto flex min-h-screen w-full sm:max-w-2xl sm:flex-row ">
      {/* TODO: サイドメニューを実装し次第入れる */}
      <div className="w-[147px] border-l">サイドメニュー</div>
      <div className="flex-1 border">
        <div className="flex h-12 items-center justify-center border-b">
          <p className="font-bold">買い物リスト</p>
        </div>
        {children}
      </div>
    </div>
  )
}
