import { ArrowLeftIcon } from "src/components/ArrowLeftIcon"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex w-full min-h-screen mx-auto sm:max-w-2xl sm:flex-row ">
      {/* TODO: サイドメニューを実装し次第入れる */}
      <div className="w-[147px] border-l">サイドメニュー</div>
      <div className="flex-1 border">
        <div className="flex p-3">
          <a href="#" className="px-1">
            <ArrowLeftIcon className="w-5 h-5" />
          </a>
          <div className="bg-[#F4F2F4] flex-1 rounded">
            <input
              type="text"
              placeholder="シェフやレシピを検索"
              className="w-full p-1 bg-inherit"
            />
          </div>
        </div>
        <nav className="flex text-sm border-b">
          <a href="#" className="flex-1 py-2 text-center">
            レシピ
          </a>
          <a
            href="#"
            className="flex-1 py-2 font-bold text-center border-b-2 border-[#000000]"
          >
            シェフ
          </a>
        </nav>
        {children}
      </div>
    </div>
  )
}
