import { Inter } from "next/font/google"
import { ArrowLeftIcon } from "src/components/ArrowLeftIcon"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex w-full min-h-screen mx-auto sm:max-w-2xl sm:flex-row ">
      <div className="w-[200px] border-l">サイドメニュー</div>
      <div className="flex-1 border">
        <div className="flex p-3">
          <a href="#" className="px-1">
            <ArrowLeftIcon className="w-5 h-5" />
          </a>
          <div className="bg-[#F4F2F4] flex-1 rounded">
            <input
              type="text"
              placeholder="シェフやレシピを検索"
              className="w-full p-1 bg-inherit"
            />
          </div>
        </div>
        {children}
      </div>
    </div>
  )
}
